CREATE TABLE PERSONNES 
(
id_personne SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom VARCHAR(100) NOT NULL,
prenom VARCHAR(100) NOT NULL,
num_rue CHAR(8),
rue VARCHAR(255) NOT NULL,
code_post CHAR(5) NOT NULL,
ville VARCHAR(100) NOT NULL,

PRIMARY KEY (id_personne)
);